-- 审批流程定义表
DROP TABLE IF EXISTS workflow;
CREATE TABLE workflow (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '流程ID',
    name VARCHAR(100) NOT NULL COMMENT '流程名称',
    description VARCHAR(500) DEFAULT NULL COMMENT '流程描述',
    version INT DEFAULT 1 COMMENT '版本号',
    status TINYINT DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批流程定义表';
